name: Markdown to PDF

on:
  push:
    branches: [ "main" ]

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Convert resume.md
        run: |-
          npm i -g md-to-pdf
          md-to-pdf resume.md --pdf-options '{"format":"letter","margin":"10mm 20mm"}'
