name: Markdown to PDF

on:
  push:
    branches: [ "main" ]
    paths:
      - resume.md

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Convert resume.md
        run: |-
          npm i -g md-to-pdf@5.2.4
          md-to-pdf resume.md --pdf-options '{"format":"letter","margin":"10mm 15mm"}' --css 'body { font-family: Monospace; }'

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Generated PDF
